---
permalink: online-help/concept-security-dashboard.html 
sidebar: sidebar 
keywords:  
summary: Active IQ Unified Manager 대시보드에서 보안 패널을 사용하거나 사용하지 않도록 설정할 수 있습니다. 이 기능을 활성화하면 규정 준수 모니터링 및 관련 보안 이벤트 및 관리 작업에 대한 설정을 사용자 지정할 수도 있습니다. 
---
= 보안 대시보드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager 대시보드에서 보안 패널을 사용하거나 사용하지 않도록 설정할 수 있습니다. 이 기능을 활성화하면 규정 준수 모니터링 및 관련 보안 이벤트 및 관리 작업에 대한 설정을 사용자 지정할 수도 있습니다.

[NOTE]
====
관리자 역할을 가진 사용자만 이러한 설정을 편집할 수 있습니다.

====
ONTAP 클러스터, 스토리지 VM 및 볼륨에 대한 보안 기준은 ONTAP 9에 대한 NetApp 보안 강화 가이드에 정의된 권장 사항을 기준으로 평가됩니다. 대시보드의 보안 패널에는 클러스터, 스토리지 VM 및 볼륨의 보안 준수 상태가 표시됩니다. 이 기능을 활성화하면 보안 위반이 있는 클러스터 또는 스토리지 VM에 대한 보안 이벤트도 생성됩니다.



== 설정 사용자 정의

이 기능을 활성화하면 ONTAP 환경에 맞게 규정 준수 모니터링에 대한 설정을 사용자 지정할 수 있습니다. 이러한 설정은 관련 보안 이벤트 및 관리 작업을 트리거합니다. 다음 단계를 수행하십시오.

. 사용자 정의 * 를 클릭합니다. 보안 대시보드 설정 사용자 지정 팝업이 나타납니다.
. ONTAP 클러스터에 대한 사용자 정의 설정을 활성화 또는 비활성화하려면 클러스터에 대한 * 일반 설정 * 선택을 확장합니다. 클러스터 규정 준수를 사용자 지정하는 옵션에 대한 자세한 내용은 을 참조하십시오 link:reference-cluster-compliance-categories.adoc["* 클러스터 규정 준수 범주 *"].
. 스토리지 VM에 대한 사용자 지정 설정을 활성화하거나 비활성화하려면 스토리지 VM에 대한 * 일반 설정 * 을 확장합니다. 스토리지 VM 규정 준수를 사용자 지정하는 옵션에 대한 자세한 내용은 를 참조하십시오 link:reference-svm-compliance-categories.adoc["스토리지 VM 규정 준수 범주"].
. ONTAP에서 AutoSupport 메시지를 보내는 데 HTTPS 전송을 사용할지 여부를 지정할 수도 있습니다.
. 인증 설정을 활성화하면 기본 ONTAP 관리자 사용자에 대한 알림이 Unified Manager에서 발생합니다.

