---
permalink: online-help/reference-aggregate-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: 다음 필드는 집계 용량 및 활용도 보고서에서 사용할 수 있으며 사용자 지정 보기 및 보고서에서 사용할 수 있습니다. 
---
= 용량 필드를 집계합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
다음 필드는 집계 용량 및 활용도 보고서에서 사용할 수 있으며 사용자 지정 보기 및 보고서에서 사용할 수 있습니다.

* * 집계 *
+
애그리게이트 이름입니다.

* * 일일 성장률 % *
+
총 24시간마다 발생하는 성장률입니다.

* * 일 대 전체 *
+
Aggregate가 전체 용량에 도달하기 전까지 남은 예상 일 수입니다.

* * 초과 커밋 용량 % *
+
이 집계 값을 백분율로 나타낸 것입니다.

* * 사용 가능한 데이터 % *
+
사용 가능한 데이터 용량을 백분율로 표시합니다.

* * 사용 가능한 데이터 용량 *
+
사용 가능한 데이터 용량입니다.

* * 사용된 데이터 % *
+
사용된 데이터 용량을 백분율로 나타낸 것입니다.

* * 사용된 데이터 용량 *
+
사용된 데이터 용량입니다.

* * 총 데이터 용량 *
+
총 데이터 용량(사용된 용량 및 사용 가능한 용량)

* * 사용된 논리적 공간 *
+
ONTAP 스토리지 효율성 기술을 사용할 때의 절감 효과를 적용하지 않고 aggregate에 저장되는 데이터의 실제 크기입니다.

* * Snapshot Reserve Available % *
+
스냅샷 복사본에 사용할 수 있는 공간의 비율입니다.

* * Snapshot Reserve Available Capacity *
+
스냅샷 복사본에 사용할 수 있는 공간의 양입니다.

* * 사용된 스냅숏 예비 공간 % *
+
스냅샷 예약의 스냅샷 복사본이 사용하는 공간 크기를 백분율로 표시한 것입니다.

* * Snapshot Reserve Used Capacity *
+
스냅샷 예약에서 스냅샷 복사본이 사용하는 공간의 양입니다.

* * 스냅샷 예비 공간 총 용량 *
+
총 스냅샷 예약 용량입니다.

* * 사용된 클라우드 계층 공간 *
+
클라우드 계층에서 현재 사용 중인 데이터 용량의 양입니다.

* * 클라우드 계층 *
+
ONTAP에서 생성한 클라우드 계층 오브젝트 저장소의 이름입니다.

* * 시/도 *
+
애그리게이트의 현재 상태입니다.

* * 유형 *
+
집계 유형:

+
** HDD
** 하이브리드
+
HDD와 SSD를 결합하지만 Flash Pool은 활성화되지 않았습니다.

** 하이브리드(Flash Pool)
+
HDD와 SSD의 결합과 Flash Pool이 설정되었습니다.

** SSD를 지원합니다
** SSD(FabricPool)
+
SSD와 클라우드 계층을 결합합니다

** HDD(FabricPool)
+
HDD와 클라우드 계층 결합

** VMDisk(SDS)
+
가상 머신 내의 가상 디스크

** VMDisk(FabricPool)
+
가상 디스크와 클라우드 계층을 결합합니다

** LUN(FlexArray)


* * RAID 유형 *
+
RAID 구성 유형입니다.

* * SnapLock 유형 *
+
집계 SnapLock 유형입니다. 가능한 값은 규정 준수, 엔터프라이즈, 비 SnapLock입니다.

* * HA 쌍 *
+
2개의 노드를 형성하여 얻은 HA 쌍 값입니다.

* * 노드 *
+
Aggregate가 포함된 노드의 이름입니다.

* * 클러스터 *
+
클러스터 이름입니다. 클러스터 이름을 클릭하여 해당 클러스터의 용량 세부 정보 페이지로 이동할 수 있습니다.

* * 클러스터 FQDN *
+
클러스터의 FQDN(정규화된 도메인 이름)입니다.


