---
permalink: online-help/reference-lag-thresholds-for-unmanaged-relationships-page.html 
sidebar: sidebar 
keywords:  
summary: 관계 임계값 페이지에서 관리되지 않는 보호 관계에 대한 전역 지연 경고 및 오류 임계값을 구성할 수 있으므로 지연 또는 임계값 오류가 발생할 때 알림을 받고 조치를 취할 수 있습니다. 이러한 설정에 대한 변경 사항은 다음 예약된 업데이트 중에 적용됩니다. 
---
= 관계 임계값 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관계 임계값 페이지에서 관리되지 않는 보호 관계에 대한 전역 지연 경고 및 오류 임계값을 구성할 수 있으므로 지연 또는 임계값 오류가 발생할 때 알림을 받고 조치를 취할 수 있습니다. 이러한 설정에 대한 변경 사항은 다음 예약된 업데이트 중에 적용됩니다.

애플리케이션 관리자 또는 스토리지 관리자 역할이 있어야 합니다.

볼륨 또는 스토리지 VM의 임계값이 위반되면 이벤트가 생성됩니다. 사용자는 이러한 이벤트에 대해 수정 조치를 취할 수 있습니다. 이제 스토리지 VM 관계에 대해 이벤트가 발생하지만 스토리지 VM 재해 복구 구성 내의 구성 관계에 대해서는 이벤트가 차단됩니다. 이렇게 하면 관계에 대해 너무 많은 이벤트가 발생하는 것을 방지할 수 있습니다. 관리되지 않는 관계에 대한 지연 임계값 설정은 기본적으로 설정되며 스토리지 VM에도 제공됩니다.

지연 임계값은 지연 시간이 초과해서는 안 되는 비율을 지정합니다. 1시간의 예를 사용하여 지연 임계값이 150%로 정의된 경우 지연 시간이 1.5시간 이상일 때 이벤트를 받게 됩니다.



== 관리되지 않는 관계 영역의 지연 임계값

Lag 영역에서는 다음 조건에 대해 관리되지 않는 관계 지연 임계값을 설정할 수 있습니다.

* * 경고 *
+
지연 기간이 지연 경고 임계값과 같거나 이를 초과하는 비율을 지정합니다.

+
** 기본값은 150%입니다
** 생성된 이벤트: SnapMirror 관계 지연 경고 또는 SnapVault 관계 지연 경고
** 이벤트 심각도: 경고


* * 오류 *
+
지연 기간이 지연 오류 임계값과 같거나 이를 초과하는 비율을 지정합니다.

+
** 기본값은 250%입니다
** 생성된 이벤트: SnapMirror 관계 지연 오류 또는 SnapVault 관계 지연 오류
** 이벤트 심각도: 오류




또한 사용(Enabled) 옆의 확인란을 선택 취소하여 지연 임계값 금액에서 경고 또는 오류 이벤트가 트리거되지 않도록 설정할 수 있습니다.
