---
permalink: online-help/reference-volume-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: 이 페이지에서는 볼륨의 물리적 속성 및 논리적 속성 목록을 볼 수 있습니다. 이 정보는 성능 관련 질문에 답변하는 데 도움이 될 수 있습니다. 이 페이지의 제목은 FlexVol 볼륨을 보고 있는지 FlexGroup 볼륨을 보고 있는지에 따라 달라집니다. 
---
= 볼륨/성능 정보 페이지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 페이지에서는 볼륨의 물리적 속성 및 논리적 속성 목록을 볼 수 있습니다. 이 정보는 성능 관련 질문에 답변하는 데 도움이 될 수 있습니다. 이 페이지의 제목은 FlexVol 볼륨을 보고 있는지 FlexGroup 볼륨을 보고 있는지에 따라 달라집니다.



== 볼륨 특성

* * 유형 *
+
읽기-쓰기(RW) 또는 데이터 보호(DP)의 볼륨 유형입니다.

* * 스타일 *
+
FlexVol 또는 FlexGroup의 볼륨 스타일입니다.

* * 클러스터 *
+
이 FlexVol 볼륨 또는 FlexGroup 볼륨이 속한 클러스터의 이름입니다. 이름을 클릭하여 클러스터/성능 탐색기 페이지에 클러스터 세부 정보를 표시할 수 있습니다.

* * 애그리게이트 *
+
이 FlexVol 볼륨이 상주하는 애그리게이트의 이름 또는 FlexGroup 볼륨이 상주하는 애그리게이트 수입니다.

+
FlexVol 볼륨의 경우 이름을 클릭하여 애그리게이트/성능 탐색기 페이지에 애그리게이트 세부 정보를 표시할 수 있습니다. FlexGroup 볼륨의 경우 번호를 클릭하여 성능/애그리게이트 인벤토리 페이지에서 이 FlexGroup 볼륨에 사용된 애그리게이트를 표시할 수 있습니다.

* 스토리지 VM *
+
이 FlexVol 볼륨 또는 FlexGroup 볼륨이 속한 SVM의 이름입니다. 이름을 클릭하여 스토리지 VM/성능 탐색기 페이지에서 SVM 세부 정보를 표시할 수 있습니다.

* * 계층화 정책 *
+
볼륨에 설정된 계층화 정책입니다. 이 정책은 볼륨이 FabricPool 애그리게이트에 구축되는 경우에만 적용됩니다. 사용 가능한 정책은 다음과 같습니다.

+
** 없음. 이 볼륨의 데이터는 항상 성능 계층에 유지됩니다.
** 스냅샷만. 스냅샷 데이터만 클라우드 계층으로 자동으로 이동됩니다. 다른 모든 데이터는 성능 계층에 유지됩니다.
** 백업. 데이터 보호 볼륨에서 전송된 모든 사용자 데이터는 클라우드 계층에서 시작되지만, 나중에 클라이언트 읽기로 인해 핫 데이터가 성능 계층으로 이동할 수 있습니다.
** 자동. ONTAP에서 데이터가 "핫" 또는 "콜드" 데이터라고 결정하면 이 볼륨의 데이터가 성능 계층과 클라우드 계층 간에 자동으로 이동됩니다.
** 모두. 이 볼륨의 데이터는 항상 클라우드 계층에 있습니다.


* * RAID 유형 *
+
이 볼륨이 상주하는 애그리게이트의 성능 계층에서 사용되는 이중화 유형입니다. 가능한 유형:

+
** RAID0
** RAID4
** RAID-DP
** RAID-TEC


+
[NOTE]
====
FlexGroup 볼륨에 대해 ""해당 없음" 값이 표시됩니다. 그 이유는 구성요소 볼륨이 다른 RAID 유형의 Aggregate에 있을 수 있기 때문입니다.

====
* * 용량(사용 가능/총) *
+
볼륨에서 사용 가능한 총 스토리지 용량(GB) 및 현재 사용 가능한 스토리지 크기입니다.

* * 사용된 논리적 공간 *
+
ONTAP 스토리지 효율성 기술을 사용할 때의 절감 효과를 적용하지 않고 이 볼륨에 저장 중인 데이터의 실제 크기입니다.


