---
permalink: online-help/reference-cluster-performance-information-page.html 
sidebar: sidebar 
keywords:  
summary: 클러스터의 물리적 및 논리적 특성 목록을 보려면 Cluster/Performance Information 페이지를 사용하십시오. 이 정보는 성능 관련 질문에 답변하는 데 도움이 될 수 있습니다. 
---
= 클러스터/성능 정보 페이지입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
클러스터의 물리적 및 논리적 특성 목록을 보려면 Cluster/Performance Information 페이지를 사용하십시오. 이 정보는 성능 관련 질문에 답변하는 데 도움이 될 수 있습니다.



== 클러스터 특성

* * 관리 네트워크 인터페이스 *
+
클러스터 관리 LIF의 이름 및 LIF가 현재 사용 가능(위) 또는 사용 가능(아래) 여부를 나타냅니다.

* * IP 주소 *
+
클러스터 관리 LIF의 IPv4 또는 IPv6 주소입니다.

* FQDN *
+
클러스터 관리 LIF의 FQDN(정규화된 도메인 이름)입니다.

* OS 버전 *
+
클러스터에 설치된 ONTAP 소프트웨어의 버전입니다.

+
[NOTE]
====
클러스터의 노드에 서로 다른 버전의 ONTAP 소프트웨어가 설치되어 있는 경우, 나열된 버전이 가장 낮은 버전 번호입니다. 각 노드에 설치된 ONTAP 소프트웨어의 버전을 보려면 노드/성능 정보 페이지를 확인하십시오.

====
* * 일련 번호 *
+
클러스터의 고유 식별 번호입니다.

* * 모델/제품군 *
+
클러스터에 있는 모든 노드의 플랫폼 모델 번호 및 모델 제품군입니다.

* * 용량(사용 가능/총) *
+
클러스터에서 사용할 수 있는 총 스토리지 용량(GB)과 현재 사용 가능한 스토리지 크기입니다.

* * 사용된 논리적 공간 *
+
ONTAP 스토리지 효율성 기술을 사용할 때의 절감 효과를 적용하지 않고도 이 클러스터의 애그리게이트에 저장되어 있는 데이터의 실제 크기를 알 수 있습니다.

* * 허용된 프로토콜 *
+
이 클러스터에서 서비스할 수 있는 모든 프로토콜 목록입니다. 사용 가능한 프로토콜은 FC/FCoE, iSCSI, HTTP, NVMe, NDMP, NFS 및 CIFS에 대해 설명합니다.

* * 노드 *
+
이 클러스터의 노드 수입니다. 번호를 클릭하여 성능/노드 인벤토리 페이지에 노드를 표시할 수 있습니다.

* 스토리지 VM *
+
이 클러스터에 있는 SVM의 수 이 번호를 클릭하여 성능/스토리지 VM 인벤토리 페이지에 SVM을 표시할 수 있습니다.

* * 네트워크 인터페이스 *
+
이 클러스터에 있는 LIF의 수입니다. 번호를 클릭하여 Performance/LIF Inventory 페이지에 LIF를 표시할 수 있습니다.

* * 연락처/위치 *
+
사용 가능한 경우 이 클러스터와 관련하여 연락할 스토리지 관리자의 이름 및 클러스터의 위치입니다.


