---
permalink: online-help/reference-health-all-clusters-view.html 
sidebar: sidebar 
keywords:  
summary: '상태: 모든 클러스터 보기를 사용하면 모니터링 중인 클러스터에 대한 상태 정보를 볼 수 있습니다.' 
---
= 상태: 모든 클러스터 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
상태: 모든 클러스터 보기를 사용하면 모니터링 중인 클러스터에 대한 상태 정보를 볼 수 있습니다.

기본적으로 보기 페이지의 개체는 이벤트 중요도에 따라 정렬됩니다. 중요한 이벤트가 있는 개체가 먼저 나열되고 경고 이벤트가 있는 개체는 두 번째로 나열됩니다. 이를 통해 해결해야 할 문제를 시각적으로 즉시 확인할 수 있습니다. 클러스터 그리드의 각 클러스터에는 ONTAP System Manager에 대한 링크가 있습니다. 이 링크를 클릭하면 ONTAP 시스템 관리자에서 동일한 보호 관계를 볼 수 있습니다. System Manager*에서 보기 메뉴 옵션은 링크 중 하나로 사용할 수 있습니다. System Manager * 에서 보기 링크는 클러스터 상태, 성능 및 용량의 세부 정보 페이지에서도 사용할 수 있습니다.

페이지 위쪽에 있는 컨트롤을 사용하면 특정 보기(상태, 성능, 용량 등)를 선택하고 검색을 수행하여 특정 개체를 찾고 필터를 생성 및 적용하여 표시된 데이터 목록의 범위를 좁히고, 페이지에서 열을 추가/제거/재정렬할 수 있습니다. 페이지의 데이터를 로 내보냅니다 `.csv`, `.pdf`, 또는 `.xlsx` 파일. 페이지를 사용자 지정한 후 결과를 사용자 정의 보기로 저장한 다음 이 데이터의 보고서를 정기적으로 생성 및 이메일로 전송할 수 있습니다.

클러스터 설정 * 버튼을 사용하여 클러스터를 수정하거나 Active IQ Unified Manager에 추가할 수 있습니다. Active IQ Unified Manager에서 사용 가능한 모든 클러스터가 나열되며 각 클러스터 이름 링크를 사용하면 쉽게 탐색할 수 있도록 ONTAP 시스템 관리자 페이지에 액세스할 수 있습니다.

Annotate * 버튼을 사용하여 클러스터를 사전 정의된 주석에 연결할 수 있습니다.

을 참조하십시오 xref:reference-cluster-health-fields.adoc[클러스터 상태 필드] 이 페이지의 모든 필드에 대한 설명은 을 참조하십시오.
