---
permalink: online-help/reference-volume-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: 'Capacity:All Volumes 보기에서 다음 필드를 사용할 수 있으며 사용자 지정 보기 및 보고서에서 사용할 수 있습니다.' 
---
= 볼륨 용량 필드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Capacity:All Volumes 보기에서 다음 필드를 사용할 수 있으며 사용자 지정 보기 및 보고서에서 사용할 수 있습니다.

* * 볼륨 *
+
볼륨 이름입니다.

* * 일일 성장률 % *
+
볼륨에서 24시간마다 발생하는 성장률입니다.

* * 일 대 전체 *
+
볼륨이 전체 용량에 도달하기 전까지 남은 예상 일 수입니다.

* * 사용 가능한 데이터 % *
+
볼륨에서 사용 가능한 데이터 용량입니다.

* * 사용 가능한 데이터 용량 *
+
볼륨에서 사용 가능한 데이터 용량입니다.

* * 사용된 데이터 % *
+
볼륨에서 사용된 데이터를 백분율로 나타낸 것입니다.

* * 사용된 데이터 용량 *
+
볼륨에서 사용된 데이터 용량입니다.

* * 총 데이터 용량 *
+
볼륨의 총 데이터 용량(사용된 용량 및 사용 가능한 용량)

* * 사용된 논리적 공간 *
+
ONTAP 스토리지 효율성 기술을 사용할 때의 절감 효과를 적용하지 않고도 이 볼륨에서 데이터에 사용된 논리적 공간입니다.

* * 스냅샷 오버플로 % *
+
스냅샷 복사본에서 사용하는 데이터 공간의 비율입니다.

* * Snapshot Reserve Available % *
+
볼륨의 스냅샷 복사본에 사용할 수 있는 공간의 비율입니다.

* * Snapshot Reserve Available Capacity *
+
볼륨의 스냅샷 복사본에 사용할 수 있는 공간의 양입니다.

* * 사용된 스냅숏 예비 공간 % *
+
볼륨의 스냅샷 복사본에서 사용하는 공간의 비율입니다.

* * Snapshot Reserve Used Capacity *
+
볼륨의 스냅샷 복사본이 사용하는 공간입니다.

* * 스냅샷 예비 공간 총 용량 *
+
볼륨의 총 스냅샷 복사본 용량을 표시합니다.

* * 할당량 커밋 용량 *
+
볼륨의 할당량에 예약된 공간입니다.

* * 할당량 초과 할당 용량 *
+
시스템에서 볼륨 할당량 초과 커밋 이벤트를 생성하기 전에 할당량에 사용할 수 있는 공간입니다.

* * 총 inode 수 *
+
볼륨의 inode 수입니다.

* * inode 사용률 % *
+
볼륨에 사용된 inode 공간의 비율입니다.

* * 씬 프로비저닝 *
+
선택한 볼륨에 대해 공간 보장이 설정되어 있는지 여부를 나타냅니다. 유효한 값은 Yes 및 No입니다

* * 공간 보장 *
+
볼륨과 연결된 스토리지 보증 옵션입니다.

* * Autogrow *
+
공간이 부족할 때 볼륨 크기가 자동으로 증가하는지 여부를 나타냅니다.

* * 스냅샷 자동 삭제 *
+
스냅샷 복사본의 자동 삭제를 설정 또는 해제할지 여부를 나타냅니다.

* * 데이터 중복 제거 *
+
볼륨에 대해 중복 제거가 설정되었는지 여부를 나타냅니다.

* * 압축 *
+
볼륨에 대해 압축이 활성화되어 있는지 또는 비활성화되어 있는지 여부

* * 시/도 *
+
내보내는 볼륨의 상태입니다.

* * 보호 역할 *
+
볼륨에 대해 설정된 보호 역할입니다.

* * SnapLock 유형 *
+
볼륨이 SnapLock 볼륨인지 또는 비 SnapLock 볼륨인지를 나타냅니다.

* * SnapLock 만료 날짜 *
+
SnapLock 만료 날짜입니다.

* * 계층화 정책 *
+
볼륨에 대해 설정된 계층화 정책입니다. FabricPool 지원 애그리게이트에만 구축할 수 있습니다.

* * 캐싱 정책 *
+
선택한 볼륨과 연결된 캐싱 정책입니다.

+
정책에 따라 볼륨에 대한 Flash Pool 캐싱이 수행되는 방법이 나와 있습니다. 캐시 정책에 대한 자세한 내용은 상태: 모든 볼륨 보기를 참조하십시오.

* * 캐시 보존 우선순위 *
+
캐시된 풀을 유지하는 데 사용되는 우선 순위입니다.

* 스토리지 VM *
+
볼륨을 포함하는 SVM(스토리지 가상 시스템)의 이름입니다.

* * 클러스터 *
+
볼륨이 상주하는 클러스터의 이름입니다. 클러스터 이름을 클릭하여 해당 클러스터의 상태 세부 정보 페이지로 이동할 수 있습니다.

* * 클러스터 FQDN *
+
클러스터의 FQDN(정규화된 도메인 이름)입니다.


