---
permalink: online-help/reference-backup-settings-dialog-box.html 
sidebar: sidebar 
keywords:  
summary: 백업 설정 대화 상자는 MySQL 및 NetApp Snapshot 백업 모두의 설정을 구성하는 데 사용됩니다. 구성된 백업에 따라 백업 설정 대화 상자에 관련 필드가 나타납니다. MySQL 데이터베이스 백업의 경우 선택한 Active IQ Unified Manager 인스턴스의 백업 일정, 보존 수 및 백업 경로를 정의할 수 있습니다. 
---
= 백업 설정 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
백업 설정 대화 상자는 MySQL 및 NetApp Snapshot 백업 모두의 설정을 구성하는 데 사용됩니다. 구성된 백업에 따라 백업 설정 대화 상자에 관련 필드가 나타납니다. MySQL 데이터베이스 백업의 경우 선택한 Active IQ Unified Manager 인스턴스의 백업 일정, 보존 수 및 백업 경로를 정의할 수 있습니다.

다음 데이터베이스 백업 설정을 변경할 수 있습니다.

* * 클러스터 *
+
Unified Manager 데이터를 호스팅할 스토리지 시스템의 클러스터 관리 IP를 제공해야 합니다.

* 볼륨 *
+
Unified Manager 데이터를 호스트하기 위한 전용 LUN이 포함된 볼륨의 이름을 제공해야 합니다.

* 스토리지 VM *
+
Unified Manager 데이터를 호스트하기 위한 전용 LUN이 포함된 볼륨이 있는 스토리지 VM의 이름을 제공해야 합니다.

* * LUN *
+
백업이 NetApp Snapshot 유형일 때 Unified Manager 데이터가 호스팅되는 LUN의 이름을 제공해야 합니다.

* * 마운트 경로 *
+
MySQL 데이터베이스 덤프 백업 방법을 사용하는 경우 이 필드는 백업 파일을 저장할 위치의 경로를 지정합니다. 스냅샷 백업 방법을 사용할 때 이 위치에 백업이 저장될 클러스터, 스토리지 VM 및 볼륨이 표시됩니다.

+
다음 표에는 여러 운영 체제의 백업 경로 형식 및 기본 위치가 나와 있습니다.

+
[cols="2*"]
|===
| 호스트 운영 체제입니다 | 백업 경로 형식입니다 


 a| 
가상 어플라이언스
 a| 
`/opt/netapp/data/ocum-backup`



 a| 
Red Hat Enterprise Linux 또는 CentOS Linux
 a| 
`/data/ocum-backup`



 a| 
Microsoft Windows
 a| 
Windows의 경우 마운트 경로를 제공해야 합니다. 예를 들어, 마운트 경로가 "D" 드라이브인 경우 마운트 경로를 로 제공해야 합니다 `D:`

|===
* * 보존 횟수 *
+
Unified Manager에서 유지할 최대 백업 수를 지정합니다. 기본값은 10입니다.

* * 매일 예약 *
+
시간을 사용하여 일별 백업 스케줄을 지정합니다.

* * 예약된 주 *
+
요일 및 시간으로 주별 백업 스케줄을 지정합니다.

* * 없음 *
+
백업이 생성되지 않도록 지정합니다.


