---
permalink: online-help/reference-cluster-capacity-fields.html 
sidebar: sidebar 
keywords:  
summary: 'Capacity:All Clusters 보기에서 사용할 수 있는 필드는 사용자 지정 보기 및 보고서에서 사용할 수 있습니다.' 
---
= 클러스터 용량 필드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Capacity:All Clusters 보기에서 사용할 수 있는 필드는 사용자 지정 보기 및 보고서에서 사용할 수 있습니다.

* * 클러스터 *
+
클러스터 이름입니다. 클러스터 이름을 클릭하여 해당 클러스터의 용량 세부 정보 페이지로 이동할 수 있습니다.

* * 클러스터 FQDN *
+
클러스터의 FQDN(정규화된 도메인 이름)입니다.

* * HA 쌍 *
+
2개의 노드를 형성하여 얻은 HA 쌍 값입니다.

* * 총 물리적 용량 *
+
배열에 있는 모든 디스크의 총 물리적 용량을 표시합니다.

* * 구성되지 않은 물리적 용량 *
+
컨테이너 유형이 애그리게이트, 부분, 스페어 또는 공유 이외의 구성되지 않은 디스크 용량입니다. 이 용량은 ONTAP에서 디스크의 물리적 용량보다 항상 높습니다. 예를 들어, 2TB 디스크를 예로 들 수 있습니다. 디스크의 물리적 용량은 ONTAP에서 1.6TB이고 Unified Manager에서 구성되지 않은 물리적 용량은 1.8TB입니다.

* * 총 용량 합계 *
+
사용자가 사용할 수 있는 총 Aggregate 크기입니다. 여기에는 스냅샷 복사본 예약이 포함됩니다.

* * 사용된 총 용량 *
+
Aggregate에서 이미 사용 중인 용량입니다. 여기에는 볼륨, LUN 및 기타 스토리지 효율성 기술에서 사용하는 용량이 포함됩니다.

* * 사용되지 않은 용량 집계 *
+
Aggregate에 추가 데이터를 저장하기 위해 사용 가능한 용량입니다. 여기에는 스냅샷 복사본 예약이 포함됩니다.

* * 사용된 논리적 공간 *
+
ONTAP 스토리지 효율성 기술을 사용할 때의 절감 효과를 적용하지 않고도 이 클러스터의 모든 애그리게이트에 저장되어 있는 데이터의 실제 크기를 알 수 있습니다.

* * 데이터 감소 *
+
구성된 ONTAP 스토리지 효율성 설정을 기반으로 한 데이터 축소율입니다.

* * 할당된 LUN 용량 *
+
매핑된 LUN의 용량입니다.

* * 할당되지 않은 LUN 용량 *
+
호스트에 매핑되지 않은 모든 LUN의 용량입니다.

* * 볼륨 총 용량 *
+
볼륨의 총 용량(사용된 용량 및 미사용 용량)

* * 사용된 볼륨 용량 *
+
볼륨의 사용된 용량입니다.

* * 볼륨 미사용 용량 *
+
볼륨의 미사용 용량입니다.

* * 볼륨 보호 용량 *
+
SnapMirror 및 SnapVault가 활성화된 볼륨의 용량입니다.

* * 사용된 클라우드 계층(라이센스 필요) *
+
FabricPool 라이센스가 필요한 스토리지 공급자 경우 클라우드 계층의 데이터에 사용되는 공간입니다.

* * 사용된 클라우드 계층(기타) *
+
StorageGRID 시스템과 ONTAP S3 프로토콜 저장소용 클라우드 계층 데이터에 사용되는 FabricPool 라이센스가 필요하지 않습니다.

* * 모델/제품군 *
+
클러스터의 모델 또는 패밀리 이름입니다.

* OS 버전 *
+
시스템에 설치된 ONTAP 버전입니다.

* * 연락처 *
+
클러스터의 연락처 정보입니다.

* * 위치 *
+
클러스터의 위치입니다.


