---
settings:
  name: Active IQ Unified Manager 9.9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: Unified Manager를 참조하십시오
    url: "/active-iq-unified-manager-99"
    version-number: '9.9'
  - name: Unified Manager를 참조하십시오
    url: "/active-iq-unified-manager-98"
    version-number: '9.8'
  - name: Unified Manager를 참조하십시오
    url: "/active-iq-unified-manager-97"
    version-number: '9.7'
  - name: Unified Manager를 참조하십시오
    url: "/oncommand-unified-manager-95"
    version-number: '9.5'
  langs: ko-kr,us-en,ja-jp,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Active IQ Unified Manager 9.9 문서
    url: "/index.html"
  - title: 릴리스 정보
    url: "/release-notes.html"
  - title: 시작하십시오
    entries:
    - title: VMware vSphere를 위한 빠른 시작 설치
      url: "/qsg-vapp.html"
    - title: Linux용 빠른 시작 설치
      url: "/qsg-linux.html"
    - title: Windows용 빠른 시작 설치
      url: "/qsg-windows.html"
  - section: install-vapp
  - section: install-linux
  - section: install-windows
  - section: config
  - section: online-help
  - section: performance-checker
  - section: health-checker
  - section: data-protection
  - section: reporting
  - section: api-automation
  - title: 법적 고지
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: 시작하십시오
    links:
    - title: 릴리즈 노트
      url: release-notes.html
    - title: VMware vSphere를 위한 빠른 시작 설치
      url: qsg-vapp.html
    - title: Linux용 빠른 시작 설치
      url: qsg-linux.html
    - title: Windows용 빠른 시작 설치
      url: qsg-windows.html
  - title: Configure Unified Manager를 설치합니다
    links:
    - title: VMware vSphere 시스템에 업그레이드를 설치합니다
      url: install-vapp/concept-requirements-for-installing-unified-manager.html
    - title: Linux 시스템에 업그레이드를 설치합니다
      url: install-linux/concept-requirements-for-installing-unified-manager.html
    - title: Windows 시스템에 업그레이드를 설치합니다
      url: install-windows/concept-requirements-for-installing-unified-manager.html
    - title: Unified Manager를 구성합니다
      url: config/concept-configuring-unified-manager.html
  - title: 성능 모니터링
    links:
    - title: 성능 임계값
      url: performance-checker/concept-managing-performance-thresholds.html
    - title: 클러스터 성능
      url: performance-checker/concept-monitoring-cluster-performance-from-the-dashboard.html
    - title: QoS 정책 그룹
      url: performance-checker/concept-managing-performance-using-qos-policy-group-information.html
  - title: 더 많은 리소스
    links:
    - title: Unified Manager 비디오
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
    - title: Unified Manager 블로그
      url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish_date_mktg%20descending&layout=card&f:@facet_language_mktg=[English]
    - title: 최신 버전의 Active IQ Unified Manager 설명서
      url: https://docs.netapp.com/us-en/active-iq-unified-manager/index.html
