---
permalink: api-automation/concept-events-api.html 
sidebar: sidebar 
keywords:  
summary: 관리 서버 범주의 이벤트 및 시스템 API를 사용하면 데이터 센터에서 모니터링되는 클러스터에 대해 생성되는 이벤트를 검색하고 Active IQ Unified Manager 환경에서 인스턴스 세부 정보를 각각 볼 수 있습니다. 
---
= 이벤트 및 시스템 세부 정보 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
를 클릭합니다 `events` 및 `system` 의 API를 참조하십시오 `management-server` 범주를 사용하면 데이터 센터에서 모니터링되는 클러스터에 대해 생성되는 이벤트를 검색하고 Active IQ Unified Manager 환경에서 인스턴스 세부 정보를 각각 볼 수 있습니다.



== 이벤트 보기

를 사용합니다 `/management-server/events` API를 사용하면 데이터 센터의 이벤트(내역 데이터 포함)를 쿼리할 수 있습니다. 이름, 영향 수준, 영향 영역, 심각도, 특정 이벤트를 보려면 상태, 리소스 이름 및 리소스 유형 을 참조하십시오. 리소스 유형 및 영역 매개 변수는 이벤트가 발생한 스토리지 객체에 대한 정보를 반환하고 영향 영역은 가용성, 용량, 구성, 보안 등과 같이 이벤트가 발생한 문제에 대한 정보를 반환합니다. 보호 및 성능.

이벤트 키를 사용하여 특정 이벤트의 세부 정보를 쿼리하고 리소스에 대한 다음 작업 집합을 실행할 수도 있습니다.

[cols="4*"]
|===
| 범주 | HTTP 동사 | 경로 | 설명 


 a| 
관리 - 서버
 a| 
가져오기
 a| 
`/management-server/events`
 a| 
응답 본문은 해당 데이터 센터에서 쿼리된 이벤트의 이벤트 세부 정보로 구성됩니다.



 a| 
관리 - 서버
 a| 
가져오기
 a| 
`+/management-server/events/{key}+`
 a| 
특정 이벤트를 쿼리하려면 이 API를 실행합니다. 세부 정보를 보려면 작업의 이벤트 키를 입력합니다. 응답 본문은 해당 이벤트의 세부 정보로 구성됩니다.

|===


== 시스템 세부 정보 보기

를 사용합니다 `/management-server/system` API를 사용하면 Unified Manager 환경의 인스턴스별 세부 정보를 쿼리할 수 있습니다. API는 시스템에 설치된 Unified Manager 버전, UUID, 공급업체 이름, 호스트 OS, 이름 등과 같은 제품 및 서비스에 대한 정보를 반환합니다. Unified Manager 인스턴스에서 실행 중인 서비스에 대한 설명 및 상태

[cols="4*"]
|===
| 범주 | HTTP 동사 | 경로 | 설명 


 a| 
관리 - 서버
 a| 
가져오기
 a| 
`/management-server/system`
 a| 
이 API를 실행하는 데 필요한 입력 매개 변수가 없습니다. 현재 Unified Manager 인스턴스의 시스템 세부 정보가 기본적으로 반환됩니다.

|===