---
permalink: api-automation/concept-metrics-apis.html 
sidebar: sidebar 
keywords:  
summary: 'Active IQ Unified Manager는 데이터 센터에서 클러스터의 성능 데이터와 스토리지 객체를 볼 수 있도록 /datacenter 범주 아래에 API 세트를 제공합니다. 이러한 API는 클러스터, 노드, LUN, 볼륨 등 다양한 스토리지 오브젝트의 성능 데이터를 애그리게이트 및 스토리지 VM:' 
---
= 성능 메트릭 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Active IQ Unified Manager에서는 아래에 API 세트를 제공합니다 `/datacenter` 범주를 사용하면 데이터 센터에서 클러스터 및 스토리지 오브젝트의 성능 데이터를 볼 수 있습니다. 이러한 API는 클러스터, 노드, LUN, 볼륨 등 다양한 스토리지 오브젝트의 성능 데이터를 애그리게이트 및 스토리지 VM:

를 클릭합니다 `/metrics` 및 `/analytics` API를 사용하면 성능 메트릭에 대한 다양한 뷰를 볼 수 있으며, 이를 사용하여 데이터 센터의 다음 스토리지 개체에 대한 다양한 세부 정보 레벨로 드릴다운할 수 있습니다.

* 클러스터
* 노드
* 스토리지 VM
* 애그리게이트
* 볼륨
* LUN을 클릭합니다


다음 표에서는 을 비교합니다 `/metrics` 및 `/analytics` 검색된 성능 데이터의 세부 사항을 API에서 확인합니다.

[cols="2*"]
|===
| 메트릭 | 분석 


 a| 
단일 객체에 대한 성능 세부 정보입니다. 예를 들면, 입니다 `+/datacenter/cluster/clusters/{key}/metrics+` API를 사용하려면 클러스터 키를 로 입력해야 합니다 `path` 해당 특정 클러스터에 대한 메트릭을 검색하는 데 사용되는 매개 변수입니다.
 a| 
데이터 센터에서 동일한 유형의 여러 객체에 대한 성능 세부 정보입니다. 예를 들면, 입니다 `/datacenter/cluster/clusters/analytics` API는 데이터 센터에 있는 모든 클러스터의 집합적 메트릭을 검색합니다.



 a| 
검색할 시간 간격 매개 변수를 기반으로 스토리지 객체에 대한 성능 메트릭 샘플
 a| 
특정 기간(72시간 이상) 동안 특정 유형의 스토리지 객체에 대한 높은 수준의 성능 집계값입니다.



 a| 
노드나 클러스터의 세부 정보와 같이 개체의 기본 세부 정보가 검색됩니다.
 a| 
특정 세부 정보가 검색되지 않습니다.



 a| 
읽기, 쓰기, 합계 등의 단일 개체에 대해 일정 기간 동안의 최소, 최대 및 평균 성능 값과 같은 누적 카운터가 검색됩니다. 및 기타 카운터. 예를 들면, 입니다 `+/datacenter/cluster/nodes/{key}/metrics+` API는 노드에 대해 다음과 같은 세부 정보(특히)를 검색합니다.

[listing]
----
 {
      "iops": {
        "local": {
          "others": 100.53,
          "read": 100.53,
          "total": 100.53,
          "write": 100.53
        },
        "others": 100.53,
        "read": 100.53,
        "total": 100.53,
        "write": 100.53
      },
      "latency": {
        "others": 100.53,
        "read": 100.53,
        "total": 100.53,
        "write": 100.53
      },
      "performance_capacity": {
        "available_iops_percent": 0,
        "free_percent": 0,
        "system_workload_percent": 0,
        "used_percent": 0,
        "user_workload_percent": 0
      },
      "throughput": {
        "other": 100.53,
        "read": 100.53,
        "total": 100.53,
        "write": 100.53
      },
---- a| 
동일한 형식의 모든 개체에 대해 집계된 단일 값이 표시됩니다. 예를 들면, 입니다 `/datacenter/cluster/nodes/analytics` API는 모든 노드에 대해 다음 값(다른 값 중)을 검색합니다.

[listing]
----
 {
      "iops": 2757.5723,
      "latency": 0.8266,
      "throughput": 13254.6992,
      "utilization_percent": 58.6488,
      "period": 72,
      "performance_capacity": {
        "used_percent": 63.5317,
        "available_iops_percent": 60731.3086
      },
----


 a| 
시간 범위 및 예제 데이터는 데이터의 시간 범위인 다음 일정을 기반으로 합니다. 예: 1h, 12h, 1d, 2D, 3D, 15d, 1W, 1m, 2m, 3m, 6개월 범위가 3일(72시간)을 초과하는 경우 1시간 샘플이 수집되고, 그렇지 않은 경우 5분 샘플이 제공됩니다. 각 시간 범위의 기간은 다음과 같습니다.

* 1시간: 5분 동안 샘플링한 최근 시간에 대한 메트릭입니다.
* 12h: 5분 동안 샘플링한 최근 12시간 동안의 메트릭입니다.
* 1D: 5분 동안 샘플링한 가장 최근 날짜의 메트릭
* 2D: 5분 동안 샘플링한 최근 2일간의 메트릭
* 3D: 5분 동안 가장 최근 3일간 샘플링한 메트릭스.
* 15d: 1시간 동안 샘플링한 최근 15일간의 지표.
* 1W: 1시간 동안 샘플링한 가장 최근 주에 대한 메트릭입니다.
* 1m: 1시간 이상 샘플링한 가장 최근 달의 측정 지표입니다.
* 2M: 1시간 동안 샘플링한 최근 2개월 동안의 메트릭
* 3M: 1시간 동안 샘플링한 최근 3개월 동안의 지표.
* 6M: 1시간 동안 가장 최근 6개월 동안 샘플링한 수치.


사용 가능한 값: 1h, 12h, 1d, 2D, 3D, 15d, 1W, 1m, 2m, 3m, 6개월

기본값: 1h
 a| 
72시간이 넘으면 3일입니다. 이 샘플이 계산되는 기간은 ISO-8601 표준 형식으로 표시됩니다.

|===
다음 표에 에 대한 설명이 나와 있습니다 `/metrics` 및 `/analytics` API에 대해 자세히 설명합니다.

[NOTE]
====
이러한 API에서 반환되는 IOPS 및 성능 메트릭은 예를 들어 두 배의 값입니다 `100.53`. 파이프(|)와 와일드카드(*) 문자로 이러한 부동 값 필터링은 지원되지 않습니다.

====
[cols="3*"]
|===
| HTTP 동사 | 경로 | 설명 


 a| 
`GET`
 a| 
`+/datacenter/cluster/clusters/{key}/metrics+`
 a| 
이 명령어는 cluster key의 input 매개 변수로 지정한 cluster의 성능 데이터(샘플 및 요약)를 조회한다. 클러스터 키 및 UUID, 시간 범위, IOPS, 처리량, 샘플 수와 같은 정보가 반환됩니다.



 a| 
`GET`
 a| 
`/datacenter/cluster/clusters/analytics`
 a| 
이 명령어는 데이터 센터의 모든 클러스터에 대한 고성능 메트릭을 조회한다. 필요한 기준에 따라 결과를 필터링할 수 있습니다. 집계된 IOPS, 처리량 및 수집 기간(시간)과 같은 값이 반환됩니다.



 a| 
`GET`
 a| 
`+/datacenter/cluster/nodes/{key}/metrics+`
 a| 
노드 키의 input 매개 변수로 지정된 노드의 성능 데이터(샘플 및 요약)를 검색합니다. 노드 UUID, 시간 범위, IOPS 요약, 처리량, 지연 시간 및 성능, 수집된 샘플 수, 활용도와 같은 정보가 반환됩니다.



 a| 
`GET`
 a| 
`/datacenter/cluster/nodes/analytics`
 a| 
이 명령어는 데이터 센터 내 모든 노드에 대해 높은 수준의 성능 지표를 조회한다. 필요한 기준에 따라 결과를 필터링할 수 있습니다. 노드 및 클러스터 키와 같은 정보와 집계된 IOPS, 처리량 및 수집 기간(시간)과 같은 값이 반환됩니다.



 a| 
`GET`
 a| 
`+/datacenter/storage/aggregates/{key}/metrics+`
 a| 
이 명령어는 aggregate key의 input parameter로 지정된 aggregate에 대한 성능 데이터(sample, summary)를 조회한다. 시간 범위, IOPS 요약, 지연 시간, 처리량 및 성능 용량, 각 카운터에 대해 수집된 샘플 수, 사용된 비율 등의 정보가 반환됩니다.



 a| 
`GET`
 a| 
`/datacenter/storage/aggregates/analytics`
 a| 
이 명령어는 데이터 센터의 모든 애그리게이트를 위한 높은 수준의 성능 메트릭을 조회한다. 필요한 기준에 따라 결과를 필터링할 수 있습니다. 집계 및 클러스터 키와 같은 정보와 집계 IOPS, 처리량 및 수집 기간(시간)과 같은 값이 반환됩니다.



 a| 
`GET`
 a| 
`+/datacenter/storage/luns/{key}/metrics+`

`+/datacenter/storage/volumes/{key}/metrics+`
 a| 
LUN 또는 볼륨 키의 입력 매개 변수로 지정한 LUN 또는 파일 공유(볼륨)의 성능 데이터(샘플 및 요약)를 검색합니다. 읽기, 쓰기 및 총 IOPS, 지연 시간, 처리량의 최소, 최대 및 평균에 대한 요약과 같은 정보 각 카운터에 대해 수집된 샘플의 수가 반환됩니다.



 a| 
`GET`
 a| 
`/datacenter/storage/luns/analytics`

`/datacenter/storage/volumes/analytics`
 a| 
이 명령어는 데이터 센터의 모든 LUN 또는 볼륨에 대해 높은 수준의 성능 메트릭을 조회한다. 필요한 기준에 따라 결과를 필터링할 수 있습니다. 스토리지 VM 및 클러스터 키와 같은 정보와 집계 IOPS, 처리량 및 수집 기간(시간)과 같은 값이 반환됩니다.



 a| 
`GET`
 a| 
`+/datacenter/svm/svms/{key}/metrics+`
 a| 
스토리지 VM 키의 입력 매개 변수로 지정한 스토리지 VM의 성능 데이터(샘플 및 요약)를 검색합니다. 과 같이 지원되는 각 프로토콜을 기반으로 IOPS에 대한 요약입니다 `nvmf, fcp, iscsi`, 및 `nfs`, 처리량, 대기 시간 및 수집된 샘플의 수가 반환됩니다.



 a| 
`GET`
 a| 
`/datacenter/svm/svms/analytics`
 a| 
이 명령어는 데이터 센터에 있는 모든 스토리지 VM에 대한 높은 수준의 성능 메트릭을 조회한다. 필요한 기준에 따라 결과를 필터링할 수 있습니다. 스토리지 VM UUID, 집계된 IOPS, 지연 시간, 처리량 및 수집 기간(시간)과 같은 정보가 반환됩니다.



 a| 
`GET`
 a| 
`/datacenter/cluster/licensing/licenses` `+/datacenter/cluster/licensing/licenses/{key}+`
 a| 
데이터 센터의 클러스터에 설치된 라이센스의 세부 정보를 반환합니다. 필요한 기준에 따라 결과를 필터링할 수 있습니다. 라이센스 키, 클러스터 키, 만료 날짜 및 라이센스 범위와 같은 정보가 반환됩니다. 라이센스 키를 입력하여 특정 라이센스의 세부 정보를 검색할 수 있습니다.

|===