---
permalink: api-automation/concept-security-apis.html 
sidebar: sidebar 
keywords:  
summary: 보안 범주의 API를 사용하여 Active IQ Unified Manager에서 선택한 클러스터 개체에 대한 사용자 액세스를 제어할 수 있습니다. 로컬 사용자 또는 데이터베이스 사용자를 추가할 수 있습니다. 인증 서버에 속하는 원격 사용자 또는 그룹을 추가할 수도 있습니다. 사용자에게 할당한 역할의 권한에 따라 스토리지 객체를 관리하거나 Unified Manager에서 데이터를 볼 수 있습니다. 
---
= 사용자 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
에서 API를 사용할 수 있습니다 `security` Active IQ Unified Manager에서 선택한 클러스터 개체에 대한 사용자 액세스를 제어하는 범주입니다. 로컬 사용자 또는 데이터베이스 사용자를 추가할 수 있습니다. 인증 서버에 속하는 원격 사용자 또는 그룹을 추가할 수도 있습니다. 사용자에게 할당한 역할의 권한에 따라 스토리지 객체를 관리하거나 Unified Manager에서 데이터를 볼 수 있습니다.

[NOTE]
====
이러한 작업을 실행하려면 애플리케이션 관리자 역할이 있어야 합니다. Unified Manager 웹 UI를 사용하여 이러한 설정을 구성할 수도 있습니다.

====
의 API입니다 `security` 범주 를 사용합니다 `users` 매개 변수, 즉 가 아닌 사용자 이름입니다 `key` 매개 변수를 사용자 엔터티의 고유 식별자로 지정합니다.

[cols="3*"]
|===
| HTTP 동사 | 경로 | 설명 


 a| 
`GET`

`POST`
 a| 
`/security/users`

`/security/users`
 a| 
이러한 방법을 사용하여 사용자의 세부 정보를 확인하거나 Unified Manager에 새 사용자를 추가할 수 있습니다.

사용자 유형에 따라 특정 역할을 사용자에게 추가할 수 있습니다. 사용자를 추가하는 동안 로컬 사용자, 유지 관리 사용자 및 데이터베이스 사용자에 대한 암호를 제공해야 합니다.



 a| 
`GET`

`PATCH`

`DELETE`
 a| 
`+/security/users/{name}+`
 a| 
를 클릭합니다 `GET` 방법 이름, 전자 메일 주소, 역할, 권한 부여 유형 등 사용자의 모든 세부 정보를 검색할 수 있습니다. 를 클릭합니다 `PATCH` 방법을 사용하면 세부 정보를 업데이트할 수 있습니다. 를 클릭합니다 `DELETE` 방법 사용자를 제거할 수 있습니다.

|===