---
permalink: health-checker/task-configuring-netapp-snapshot-backup-from-maintenance-console.html 
sidebar: sidebar 
keywords: configure NetApp Snapshot backup,using maintenance console 
summary: 유지보수 콘솔에서 Active IQ Unified Manager 백업을 NetApp Snapshot 백업으로 구성해야 합니다. 
---
= 유지보수 콘솔에서 NetApp Snapshot 백업 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
유지보수 콘솔에서 Active IQ Unified Manager 백업을 NetApp Snapshot 백업으로 구성해야 합니다.



== 시작하기 전에

시스템에 대한 다음 세부 정보가 있어야 합니다.

* 클러스터 IP 주소입니다
* 스토리지 VM 이름입니다
* 볼륨 이름입니다
* LUN 이름입니다
* 마운트 경로
* 스토리지 시스템 자격 증명




== 단계

. Unified Manager의 유지보수 콘솔에 액세스합니다.
. 를 입력합니다 `4` 백업 복원 * 을 선택합니다.
. 를 입력합니다 `2` 를 눌러 NetApp Snapshot * 을 사용하여 백업 및 복원 * 을 선택합니다.
+
[NOTE]
====
백업 구성을 변경하려면 를 입력합니다 `3` NetApp Snapshot 백업 구성 업데이트용 암호만 업데이트할 수 있습니다.

====
. 메뉴에서 를 입력합니다 `1` Configure NetApp Snapshot Backup * 을 선택합니다.
. 를 입력합니다 `1` 필요한 정보를 제공합니다.
. 유지보수 콘솔의 사용자 이름과 암호를 입력한 다음 LUN이 호스트에 마운트되었음을 확인합니다.
+
그런 다음 이 프로세스에서 데이터 디렉토리, LUN 경로, 스토리지 VM, 볼륨, 공간 가용성 드라이브 등이 정답입니다. 백그라운드에서 진행 중인 작업은 다음과 같습니다.

+
** 서비스가 중지되었습니다
** 데이터베이스 디렉토리가 마운트된 스토리지로 이동됩니다
** 데이터베이스 디렉토리가 삭제되고 symlink가 설정됩니다
** Active IQ Unified Manager 인터페이스에서 구성이 완료되면 서비스가 다시 시작됩니다. 백업 유형은 NetApp Snapshot으로 수정되며 사용자 인터페이스에 데이터베이스 백업(스냅샷 기반)으로 반영됩니다.






== 예

백업 작업을 시작하기 전에 스냅샷 구성이 변경되었는지 확인해야 합니다. 스냅샷이 잘못될 수 있기 때문입니다. G 드라이브에서 백업을 구성하고 스냅샷을 촬영했다고 가정해 보겠습니다. 나중에 백업을 E 드라이브로 재구성하고 새 구성에 따라 데이터가 E 드라이브에 저장됩니다. G 드라이브에 있던 동안 생성된 스냅샷을 복원하려고 하면 G 드라이브가 존재하지 않는다는 오류와 함께 실패합니다.
